/*!
@file
In dit bestand staat de API van de configuratie van een standaard grafiek venster
 op het STM32F412 Discovery board die in RGT/DSB practica  kan worden gebruikt.

@version $Rev: 3649 $
@author $Author: ewout $

@copyright Copyright 2017-2018 Hogeschool van Arnhem en Nijmegen, ir drs E.J Boks

$URL: http://svn.hanese.nl/docenten/svn/ewout/vakken/algemeen/software/STM32/STM32Basis/HAL/gemeenschappelijk/Libraries/Middlewares/ST/STemWin/BSP/STM32F412G-Discovery/standaardGrafiekVenster.h $
$Id: standaardGrafiekVenster.h 3649 2019-10-03 16:34:04Z ewout $ */

/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

//#include "DIALOG.h"
#ifdef StemWinAanwezig

#include <WM.h>

namespace StandaardGrafiekVenster
{
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_GRAPH_0  (GUI_ID_USER + 0x01)


	WM_HWIN maakVenster();
	void sluitVenster(const WM_HWIN);
	
};

#endif
/*************************** End of file ****************************/
