// -*- C++ -*- generated by wxGlade 0.4 on Fri Feb 16 10:31:09 2007

/* $Id: gemwaarde.h 323 2023-03-17 10:03:47Z ewout $                               */

/************ Opdracht 2 voor ESE DSB practicum                      ***************/
/************ Werk deze code verder uit volgens de opdracht                 ********/
/************ Copyright 2006-2016 Hogeschool van Arnhem en Nijmegen         ********/
/************ ir drs E.J Boks                                               ********/

/* $Id: gemwaarde.h 323 2023-03-17 10:03:47Z ewout $                              */

#ifndef GEMWAARDE_H
#define GEMWAARDE_H

 /* GUI includes */
#include <wx/wx.h>

#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

#include <wx/font.h>
#include <wx/file.h>
#include <wx/dynarray.h>

#include <grafiekVenster.h>
#include <desktopApp.h>

#if defined (InterfaceTaalEnglish)
#define GrafiekVenster GraphicsWindow
#endif

class GemWaardeVenster: public wxFrame {
public:
    // begin wxGlade: GemWaardeVenster::ids
    // end wxGlade

    GemWaardeVenster(DesktopApp &, int id, 
					 const wxString& title, 
					 const wxPoint& pos=wxDefaultPosition, 
					 const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

    ~GemWaardeVenster();

protected:

    // begin wxGlade: GemWaardeVenster::attributes
    wxMenuBar* venster_menubar;
    DynamischGrafiekVenster* grafiek;
    wxRadioBox* filterSelectionRadioBox;
    wxSlider* avgValueSlider;
    wxButton* tekenButton;
    wxButton* dataLadenKnop;
    wxButton* eindeKnop;
    wxPanel* panel_1;
    // end wxGlade

private:

    // begin wxGlade: GemWaardeVenster::methods
    void set_properties();
    void do_layout();
    // end wxGlade

	DesktopApp& app;

	bool dataGeladen=false;
	bool gemVeranderd=true;
	wxArrayDouble data;

	const int doubleToInt = 10000;

	const wxPen origPen, gemWaardePen,rasterPen;
	const wxSize grafiekGrootte;

	void lopendGemiddeldeGrootteUpdateHandler(wxUpdateUIEvent &);
	void tekenUpdateHandler(wxUpdateUIEvent &);

	void dataLadenHandler(wxCommandEvent &event); // wxGlade: <event_handler>
	void eindeHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void gemInstelwaardeVeranderdHandler(wxScrollEvent &event); // wxGlade: <event_handler>
    void filterGeuzeGemaaktHandler(wxCommandEvent &event); // wxGlade: <event_handler>

	/*! @brief Dit is de funktie waarin de studentcode moet worden geimplementeerd. */
    void drawDataHandler(wxCommandEvent &event); // wxGlade: <event_handler>

    wxString dataPad;
    wxConfig * const appConfig;
	
	const wxString DemoTekst;

	DECLARE_EVENT_TABLE();

	typedef enum
	{
		GrafiekVensterID=0,
		FilterSelectionRadioBoxID,
		AvgValueSliderID,
		TekenGrafiekID,
		LaatsteEventID
	} EventHandlerIDs;

	static constexpr auto valutaTekenOffset = 0.6;
	

	
}; // wxGlade: end class


class GemWaardeOpdracht : public DesktopApp
{
public:
	GemWaardeOpdracht();
	

    bool OnInit();

protected:

private:

};

DECLARE_APP(GemWaardeOpdracht)

#endif // GEMWAARDE_H


